Repository MozillaFoundation/foundation.mozilla.org, pull requests merged in 2020-05, with the labels that each got.

#4581 Reorder the PNI product fields in the CMS to match the on-page presentation of those fields.
  network-api/networkapi/buyersguide/pagemodels/products/base.py
  network-api/networkapi/buyersguide/pagemodels/products/general.py
  network-api/networkapi/buyersguide/pagemodels/products/software.py
  network-api/networkapi/wagtailpages/utils.py
Labels: ready-to-merge

#4450 Make a11y testing pass the "global components" integration tests.
  README.md
  cypress/integration/a11y/global_component_assessments.js
  cypress/integration/a11y/global_variables.js
  cypress/plugins/index.js
  docs/accessibility.md
  package.json
Labels: engineering, ready-to-merge

#4594 Fix misaligned icon bug on Chrome
  source/js/components/share-button-group/share-button-group.scss
Labels: ready-to-merge

#4592 Enable Debugging in VSCode using ptvsd
  .gitignore
  .vscode/launch.json
  Pipfile
  Pipfile.lock
  docker-compose.yml
  docs/local_development_with_docker.md
  env.default
  network-api/manage.py
Labels: engineering, ready-to-merge

#4591 Upgrade bootstrap from v4 alpha to v4.4.1
  network-api/networkapi/buyersguide/templates/buyersguide_home.html
  network-api/networkapi/buyersguide/templates/product_page.html
  network-api/networkapi/mozfest/templates/mozfest/404.html
  network-api/networkapi/mozfest/templates/partials/primary_heroguts.html
  network-api/networkapi/mozfest/templates/partials/primary_mozfest_nav.html
  network-api/networkapi/templates/partials/multipage_nav_mobile.html
  network-api/networkapi/templates/partials/primary_nav.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/bannered_campaign_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/blog_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/campaign_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/primary_heroguts.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/homepage.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/mini_site_name_space.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/opportunity_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube_regrets_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/static/initiatives_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/tags/mini_site_sidebar.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/tags/primary_page_menu.html
  package-lock.json
  package.json
  source/js/components/fellow-list/directory-filter-bar.scss
  source/js/components/join/join.jsx
  source/js/components/join/join.scss
  source/js/components/member-notice/member-notice.jsx
  source/js/components/petition/petition.jsx
  source/js/components/petition/petition.scss
  source/js/foundation/pages/youtube-regrets/index.js
  source/sass/buttons.scss
  source/sass/buyers-guide/bg-main.scss
  source/sass/buyers-guide/views/homepage.scss
  source/sass/mixins.scss
  source/sass/mofo-bootstrap/mofo-bootstrap.scss
  source/sass/mofo-bootstrap/overrides/_forms.scss
  source/sass/mofo-bootstrap/overrides/_variables.scss
  source/sass/utilities.scss
  source/sass/views/blog.scss
  source/sass/views/projects.scss
Labels: ready-to-merge

#4625 I4330
  app.json
  env.default
  network-api/networkapi/settings.py
  network-api/networkapi/tests.py
  network-api/networkapi/utility/middleware.py
Labels: ready-to-merge

#4614 Add styling for button active state
  source/sass/buttons.scss
  source/sass/mixins.scss
Labels: ready-to-merge

#4627 Fix YouTube Regrets UI bug and script bug
  network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube_regrets_page.html
  source/js/components/join/join.jsx
  source/js/foundation/pages/youtube-regrets/index.js
  source/js/main.js
  source/sass/views/youtube-regrets.scss
Labels: ready-to-merge

#4634 Added nowrap rule back from buttons
  source/sass/buttons.scss
Labels: ready-to-merge

#4635 live chat should be optional
  source/js/buyers-guide/analytics-events.js
Labels: ready-to-merge

#4521 setup pip-tools for local dev
  .gitignore
  .travis.yml
  Pipfile
  Pipfile.lock
  README.md
  dev-requirements.in
  dev-requirements.txt
  docker-compose.yml
  dockerfiles/Dockerfile.node
  dockerfiles/Dockerfile.python
  docs/local_development.md
  docs/local_development_with_invoke_pipenv.md
  network-api/networkapi/buyersguide/pagemodels/products/base.py
  network-api/networkapi/buyersguide/tests.py
  network-api/networkapi/management/commands/review_app_admin.py
  network-api/networkapi/utility/faker/streamfield_provider.py
  network-api/networkapi/wagtailpages/wagtail_hooks.py
  package-lock.json
  package.json
  requirements.in
  requirements.txt
  tasks.py
  travis-scripts/python-install.sh
Labels: DevOps, engineering, ready-to-merge

#4636 Shorter fake button text on homepage hero
  network-api/networkapi/wagtailpages/factory/homepage.py
Labels: ready-to-merge

#4620 SCSS breakpoint improvements
  network-api/networkapi/buyersguide/templates/primary_nav.html
  source/js/buyers-guide/components/primary-nav/primary-nav.scss
  source/sass/buyers-guide/views/homepage.scss
  source/sass/buyers-guide/views/product.scss
  source/sass/components/feature-quote.scss
  source/sass/components/primary-nav.scss
  source/sass/mozfest.scss
  source/sass/views/participate.scss
  source/sass/views/youtube-regrets.scss
Labels: ready-to-merge

#4631 Enable PNI testing
  cypress/integration/a11y/global_component_assessments.js
  cypress/integration/a11y/pni_assessments.js
Labels: ready-to-merge

#4630 Remove PNI extra code for share buttons & tweak share button styling
  source/js/buyers-guide/components/creep-vote/creep-vote.scss
  source/js/buyers-guide/components/social-share/social-share.jsx
  source/js/components/share-button-group/share-button-group.scss
Labels: ready-to-merge

#4673 switch <a> from gray-40 to gray-60 to get a good a11y contrast ratio
  source/sass/buyers-guide/components/header.scss
Labels: ready-to-merge

#4680 product name already uses h1 heading, made it an h1
  network-api/networkapi/buyersguide/templates/product_page.html
Labels: ready-to-merge

#4611 Print style for blog post page
  network-api/networkapi/templates/pages/base.html
  network-api/networkapi/templates/partials/footer.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/annotated_image_block.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/video_block.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/blog_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/related_posts.html
  source/js/components/pulse-project-list/pulse-project-list.jsx
  source/sass/buttons.scss
  source/sass/buyers-guide/views/product.scss
  source/sass/main.scss
  source/sass/mixins.scss
  source/sass/print.scss
  source/sass/type.scss
Labels: ready-to-merge

#4672 Update python to 3.7.7
  runtime.txt
Labels: DevOps, ready-to-merge

#4678 Remove PNI old mobile nav code
  network-api/networkapi/buyersguide/templates/primary_nav.html
  source/images/buyers-guide/icon-close.svg
  source/images/buyers-guide/icon-share.svg
  source/js/buyers-guide/analytics-events.js
  source/js/buyers-guide/bg-main.js
  source/js/buyers-guide/components/primary-nav/primary-nav.js
  source/js/buyers-guide/components/primary-nav/primary-nav.scss
  source/js/common/initialize-primary-nav.js
Labels: ready-to-merge

#4675 update help text for petition sp fields, and make help text always show
  network-api/networkapi/wagtailcustomization/templates/wagtailadmin/base.html
  network-api/networkapi/wagtailpages/migrations/0097_auto_20200520_1936.py
  network-api/networkapi/wagtailpages/pagemodels/campaigns.py
Labels: ready-to-merge

#4679 removed the custom GA event when adding clipboard functionality
  source/js/buyers-guide/bg-main.js
Labels: ready-to-merge

#4690 Replacing merge for squash in mergify
  .mergify.yml
Labels: DevOps, ready-to-merge

#4689 Featured blog posts
  network-api/networkapi/wagtailpages/migrations/0098_featuredblogpages.py
  network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py
  network-api/networkapi/wagtailpages/templates/wagtailpages/blog_index_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_index_feature.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/index_page.html
Labels: ready-to-merge

#4701 fixed heading skip
  network-api/networkapi/buyersguide/templates/buyersguide_home.html
Labels: ready-to-merge

#4687 Typeform block
  env.default
  network-api/networkapi/mozfest/migrations/0015_auto_20200527_1836.py
  network-api/networkapi/wagtailpages/migrations/0099_auto_20200527_1836.py
  network-api/networkapi/wagtailpages/pagemodels/base_fields.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/__init__.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/typeform_block.py
  network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/typeform_block.html
  source/js/embed-typeform.js
  source/js/main.js
Labels: ready-to-merge

#4702 fixes headings on some about pages
  network-api/networkapi/buyersguide/templates/about/about_nav.html
  network-api/networkapi/buyersguide/templates/about/methodology.html
Labels: ready-to-merge

#4700 Pni landmarks
  maintenance/static/css/main.css
  network-api/networkapi/buyersguide/templates/bg_base.html
  network-api/networkapi/templates/partials/footer.html
  network-api/networkapi/templates/partials/primary_nav.html
  source/sass/global.scss
Labels: ready-to-merge

#4695 Added protocol to the pulse domain
  .travis.yml
  app.json
  env.default
  source/js/components/pulse-project-list/pulse-project-list.jsx
Labels: ready-to-merge

#4699 fix headings and contrast
  network-api/networkapi/buyersguide/templates/product_page.html
  source/sass/buyers-guide/views/product.scss
Labels: ready-to-merge
