Repository MozillaFoundation/foundation.mozilla.org, pull requests merged in 2020-02, with the labels that each got.

#4170 remove python-coveralls and replace it with coveralls-python
  Pipfile
  Pipfile.lock
Labels: DevOps

#4203 Localize MozFest homepage
  network-api/networkapi/mozfest/migrations/0010_auto_20200213_1550.py
  network-api/networkapi/mozfest/templates/fragments/twitter_feed.html
  network-api/networkapi/mozfest/templates/mozfest/404.html
  network-api/networkapi/mozfest/templates/mozfest/mozfest-base.html
  network-api/networkapi/mozfest/templates/partials/homepage_banner.html
  network-api/networkapi/mozfest/templates/partials/mozfest_footer.html
  network-api/networkapi/mozfest/translation.py
  network-api/networkapi/settings.py
  network-api/networkapi/wagtailpages/migrations/0091_auto_20200213_1550.py
  network-api/networkapi/wagtailpages/templatetags/localization.py
  tasks.py
Labels: engineering, localization 🌎

#4179 Add a redirect decorator to redirects to the main CMS site
  .travis.yml
  network-api/networkapi/buyersguide/views.py
  network-api/networkapi/tests.py
  network-api/networkapi/utility/redirects.py
Labels: DevOps, engineering

#4240 update python to 3.7.6
  runtime.txt
Labels: DevOps

#4241 pass github access_token in headers
  network-api/networkapi/management/commands/review_app_admin.py
Labels: DevOps
