Repository MozillaFoundation/foundation.mozilla.org, pull requests merged in 2020-09, with the labels that each got.

#5098 4931 publications
  .travis.yml
  docs/local_development.md
  docs/stack.md
  network-api/networkapi/settings.py
  network-api/networkapi/wagtailpages/factory/__init__.py
  network-api/networkapi/wagtailpages/factory/publication.py
  network-api/networkapi/wagtailpages/migrations/0009_articleauthors_articlepage_publicationauthors_publicationpage.py
  network-api/networkapi/wagtailpages/models.py
  network-api/networkapi/wagtailpages/pagemodels/base.py
  network-api/networkapi/wagtailpages/pagemodels/modular.py
  network-api/networkapi/wagtailpages/pagemodels/publications/article.py
  network-api/networkapi/wagtailpages/pagemodels/publications/publication.py
  network-api/networkapi/wagtailpages/templates/wagtailpages/article_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/publication_page.html
  network-api/networkapi/wagtailpages/translation.py
Labels: ready-to-merge

#5173 Run django-modeltranslation tasks after migration task
  tasks.py
Labels: ready-to-merge

#5136 Wagtail 2.10.1
  network-api/networkapi/management/commands/load_fake_data.py
  network-api/networkapi/mozfest/factory.py
  network-api/networkapi/settings.py
  network-api/networkapi/tests.py
  network-api/networkapi/wagtailpages/factory/__init__.py
  network-api/networkapi/wagtailpages/factory/homepage.py
  network-api/networkapi/wagtailpages/factory/image_factory.py
  network-api/networkapi/wagtailpages/factory/participate_page.py
  network-api/networkapi/wagtailpages/views.py
  requirements.in
  requirements.txt
Labels: engineering

#5162 5161 - Localize a11y text for Webby award logo
  network-api/networkapi/buyersguide/templates/buyersguide_home.html
Labels: ready-to-merge

#5212 Use random.choice instead of database random ordering
  network-api/networkapi/wagtailpages/factory/homepage_cause_statement_link.py
  network-api/networkapi/wagtailpages/factory/homepage_features.py
  network-api/networkapi/wagtailpages/factory/homepage_take_action.py
Labels: ready-to-merge

#5229 update eslint to support es2018 syntax
  .eslintrc.json
Labels: ready-to-merge

#5231 Update images on RegretsReporter page
  source/images/youtube-regrets/regrets-reporter/how-it-works-step1.png
  source/images/youtube-regrets/regrets-reporter/how-it-works-step2.png
  source/images/youtube-regrets/regrets-reporter/how-it-works-step3.png
Labels: ready-to-merge

#5219 Add GA event trackings to homepage
  network-api/networkapi/templates/partials/footer.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/cause_statement.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/news_you_can_use.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/partner.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/primary_heroguts.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/take_action.html
  source/js/components/join/join.jsx
  source/js/foundation/template-js-handler/homepage.js
  source/js/foundation/template-js-handler/index.js
Labels: ready-to-merge

#5214 add breakpoints and columns to styleguide
  network-api/networkapi/wagtailpages/templates/wagtailpages/static/styleguide.html
Labels: ready-to-merge

#5062 Implement hreflang via HTTP headers
  network-api/networkapi/context_processor.py
  network-api/networkapi/settings.py
  network-api/networkapi/templates/fragments/canonical_url.html
  network-api/networkapi/templates/pages/base.html
Labels: ready-to-merge

#5262 Instruct Travis-ci to execute builds for the pni-v4-2020 branch
  .travis.yml
Labels: ready-to-merge

#5272 Update Payment pointer to MoFo Uphold account
  network-api/networkapi/buyersguide/templates/bg_base.html
  network-api/networkapi/buyersguide/views.py
  network-api/networkapi/settings.py
Labels: DevOps, ready-to-merge, unplanned

#5267 Quick PNI updates to product page intro section
  network-api/networkapi/buyersguide/templates/product_page.html
  source/images/buyers-guide/icon-product-link.svg
  source/js/buyers-guide/analytics-events.js
  source/js/buyers-guide/bg-main.js
  source/js/buyers-guide/index.js
  source/js/buyers-guide/template-js-handler/copy-link.js
  source/js/buyers-guide/template-js-handler/index.js
  source/sass/buyers-guide/views/product.scss
Labels: ready-to-merge

#5263 Nav logo fixes
  source/js/buyers-guide/components/primary-nav/primary-nav.scss
  source/sass/buyers-guide/bg-main.scss
  source/sass/components/primary-nav.scss
  source/sass/main.scss
  source/sass/mozfest.scss
  source/sass/variables.scss
Labels: ready-to-merge

#5284 Reordered fields based on design spec
  network-api/networkapi/buyersguide/templates/product_page.html
Labels: engineering, frontend

#5283 only list products from 2020 for crosslinking
  network-api/networkapi/buyersguide/pagemodels/products/base.py
Labels: Buyer's Guide 🛍, engineering

#5281 [5170] Article Page Factories
  network-api/networkapi/settings.py
  network-api/networkapi/utility/faker/streamfield_provider.py
  network-api/networkapi/wagtailpages/factory/publication.py
Labels: backend, engineering

#5280 update PNI v4 fields
  network-api/networkapi/buyersguide/factory.py
  network-api/networkapi/buyersguide/migrations/0002_auto_20200923_1817.py
  network-api/networkapi/buyersguide/pagemodels/products/base.py
  network-api/networkapi/buyersguide/pagemodels/products/general.py
  network-api/networkapi/buyersguide/pagemodels/products/software.py
  network-api/networkapi/buyersguide/templates/fragments/signup_requirement.html
  network-api/networkapi/buyersguide/templates/product_page.html
  network-api/networkapi/wagtailcustomization/__init__.py
  network-api/networkapi/wagtailcustomization/static/css/admin.css
  network-api/networkapi/wagtailpages/utils.py
Labels: Buyer's Guide 🛍, engineering

#5299 Wrapping one MozFest string for localization
  network-api/networkapi/mozfest/templates/partials/primary_mozfest_nav.html
Labels: ready-to-merge

#5307 Add wifi/bluebooth info & add a type.scss for PNI
  network-api/networkapi/buyersguide/templates/product_page.html
  source/images/buyers-guide/icon-bluetooth.svg
  source/images/buyers-guide/icon-wifi.svg
  source/sass/buyers-guide/bg-main.scss
  source/sass/buyers-guide/type.scss
  source/sass/buyers-guide/views/product.scss
Labels: ready-to-merge

#5331 MSS section updates
  network-api/networkapi/buyersguide/templates/fragments/product_criterion.html
  network-api/networkapi/buyersguide/templates/fragments/product_criterion_primary_info.html
  network-api/networkapi/buyersguide/templates/product_page.html
  source/images/buyers-guide/score/icon-star.svg
  source/sass/buyers-guide/type.scss
  source/sass/buyers-guide/views/product.scss
Labels: ready-to-merge

#5353 Exclude the job if this is the PNI feature branch
  .travis.yml
Labels: Buyer's Guide 🛍, DevOps, engineering, unplanned
