Repository MozillaFoundation/foundation.mozilla.org, pull requests merged in 2020-08, with the labels that each got.

#4895 Foundation HomePage: Take Action Section
  network-api/networkapi/wagtailpages/migrations/0006_homepage_take_action_cards.py
  network-api/networkapi/wagtailpages/pagemodels/base.py
  network-api/networkapi/wagtailpages/templates/wagtailpages/homepage.html
Labels: blocked

#5012 Feature/4885 white grey bg
  network-api/networkapi/wagtailpages/pagemodels/base.py
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/featured_stories.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/partner.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/quote.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/take_action.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/homepage.html
  source/sass/global.scss
  source/sass/wagtail.scss
Labels: engineering, frontend

#5024 Homepage factories
  network-api/networkapi/wagtailpages/factory/__init__.py
  network-api/networkapi/wagtailpages/factory/areas_of_focus.py
  network-api/networkapi/wagtailpages/factory/homepage.py
  network-api/networkapi/wagtailpages/factory/homepage_areas_of_focus.py
  network-api/networkapi/wagtailpages/factory/homepage_features.py
  network-api/networkapi/wagtailpages/factory/homepage_take_action.py
  network-api/networkapi/wagtailpages/models.py
Labels: backend, engineering

#5041 Alt text on ImageGrid block
  network-api/networkapi/mozfest/migrations/0003_auto_20200811_1657.py
  network-api/networkapi/wagtailpages/migrations/0005_auto_20200811_1657.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/image_grid.py
  network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/figure_block.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/image_grid_block.html
Labels: ready-to-merge

#5070 Sort language names alphabetically
  network-api/networkapi/templates/fragments/language_switcher.html
  network-api/networkapi/wagtailpages/templatetags/localization.py
  source/sass/glyphs.scss
Labels: ready-to-merge

#5110 Issue 5103
  source/sass/views/home.scss
Labels: engineering

#5128 how did this get in here?
  source/sass/wagtail.scss
Labels: ready-to-merge

#5138 New Homepage Localization
  network-api/networkapi/wagtailpages/migrations/0008_auto_20200827_1038.py
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/blog_authors.html
  network-api/networkapi/wagtailpages/translation.py
  source/js/components/petition/locale-strings.jsx
Labels: ready-to-merge
