Repository MozillaFoundation/foundation.mozilla.org, pull requests merged in 2020-07, with the labels that each got.

#4831 remove last parts of the old SQS integration for petitions
  env.default
  network-api/networkapi/settings.py
Labels: DevOps, ready-to-merge

#4839 Modal close button styling fix
  source/js/components/petition/donation-modal.jsx
  source/js/components/petition/donation-modal.scss
Labels: ready-to-merge

#4912 Remove accidentally committed file foundation.psql
  foundation.psql
Labels: engineering, ready-to-merge, unplanned

#4918 Slack bot - Replace attachments by blocks
  network-api/networkapi/management/commands/review_app_admin.py
Labels: DevOps, engineering, ready-to-merge

#4900 Update staging copy documentation
  docs/local_development.md
Labels: documentation, engineering, ready-to-merge

#4316 Support ISO 3166 locale codes
  network-api/networkapi/mozfest/migrations/0002_auto_20200708_2215.py
  network-api/networkapi/settings.py
  network-api/networkapi/templates/fragments/language_switcher.html
  network-api/networkapi/tests.py
  network-api/networkapi/wagtailpages/__init__.py
  network-api/networkapi/wagtailpages/migrations/0004_auto_20200708_2214.py
  network-api/networkapi/wagtailpages/templatetags/localization.py
  network-api/networkapi/wagtailpages/utils.py
Labels: engineering, localization 🌎, ready-to-merge

#4899 Minify compiled CSS file
  package-lock.json
  package.json
  postcss.config.js
Labels: ready-to-merge

#4969 remove old site in CSP
  env.default
Labels: DevOps, ready-to-merge

#4972 [Review App] fix typo in slack payload
  network-api/networkapi/management/commands/review_app_admin.py
Labels: DevOps

#4968 update to python 3.7.8
  dockerfiles/Dockerfile.python
  runtime.txt
Labels: DevOps, ready-to-merge, unplanned

#4960 Partner Section
  network-api/networkapi/wagtailpages/factory/homepage.py
  network-api/networkapi/wagtailpages/migrations/0008_homepage_partner_section.py
  network-api/networkapi/wagtailpages/pagemodels/base.py
  network-api/networkapi/wagtailpages/templates/wagtailpages/homepage.html
Labels: backend, engineering

#4965 Update footers
  maintenance/maintenance.html
  network-api/networkapi/mozfest/templates/partials/mozfest_footer.html
  network-api/networkapi/templates/partials/footer.html
  source/images/mozilla-block-white.svg
Labels: ready-to-merge

#4983 Update issue templates to make headings more legible
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/design-to-dev-handoff.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ready-to-merge
