Repository MozillaFoundation/foundation.mozilla.org, pull requests merged in 2020-04, with the labels that each got.

#4425 add sentry to PNI
  source/js/buyers-guide/bg-main.js
Labels: DevOps

#4354 Enable preload and max-requests for gunicorn
  Procfile
Labels: engineering

#4442 Make 'recent-blog-entries' component consult the BlogPageCategory object set
  network-api/networkapi/mozfest/migrations/0014_auto_20200406_2109.py
  network-api/networkapi/wagtailpages/migrations/0095_auto_20200406_2109.py
  network-api/networkapi/wagtailpages/pagemodels/blog/blog_category.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/recent_blog_entries.py
Labels: engineering

#4443 Extract more code to different files & some code optimization
  network-api/networkapi/mozfest/templates/mozfest/mozfest-base.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/profile_directory.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube_regrets_page.html
  package.json
  source/js/buyers-guide/bg-main.js
  source/js/common/template-js-handles/footer-donate-button.js
  source/js/common/template-js-handles/header-donate-button.js
  source/js/common/template-js-handles/index.js
  source/js/foundation/index.js
  source/js/foundation/inject-react/multipage-nav.js
  source/js/foundation/pages/directory-listing-filters.js
  source/js/foundation/pages/mozfest/index.js
  source/js/foundation/pages/mozfest/template-js-handler/footer-social-button.js
  source/js/foundation/pages/mozfest/template-js-handler/home-banner.js
  source/js/foundation/pages/mozfest/template-js-handler/index.js
  source/js/foundation/pages/mozfest/template-js-handler/primary-button.js
  source/js/foundation/pages/youtube-regrets/index.js
  source/js/foundation/template-js-handler/global/sticky-cta.js
  source/js/foundation/template-js-handler/index.js
  source/js/foundation/template-js-handler/window/sticky-cta.js
  source/js/foundation/template-js-handler/window/sticky-share-button-group.js
  source/js/main.js
  source/js/mozfest-ga.js
  source/js/nav-newsletter.js
  webpack.config.js
Labels: engineering

#4530 Gunicorn perf redux
  Procfile
Labels: DevOps, engineering

#4527 Add a mergify rule to merge PRs that have the ready-to-merge label
  .mergify.yml
  docs/workflow.md
Labels: DevOps, engineering

#4548 Remove 'html-entities' from dependencies
  package-lock.json
  package.json
Labels: ready-to-merge

#4551 Move mofo-bootstrap source files here and remove mofo-bootstrap npm package as a dependency
  package-lock.json
  package.json
  source/sass/buyers-guide/bg-main.scss
  source/sass/main.scss
  source/sass/mofo-bootstrap/custom/_colors.scss
  source/sass/mofo-bootstrap/custom/components/_footer.scss
  source/sass/mofo-bootstrap/mofo-bootstrap.scss
  source/sass/mofo-bootstrap/overrides/_buttons.scss
  source/sass/mofo-bootstrap/overrides/_list-group.scss
  source/sass/mofo-bootstrap/overrides/_mixins.scss
  source/sass/mofo-bootstrap/overrides/_normalize.scss
  source/sass/mofo-bootstrap/overrides/_type.scss
  source/sass/mofo-bootstrap/overrides/_variables.scss
Labels: ready-to-merge

#4550 ensures sorting in the page chooser modal
  network-api/networkapi/wagtailpages/wagtail_hooks.py
Labels: ready-to-merge

#4529 Campaign index page - publish fake page & add it to Percy test
  cypress/integration/endpoint-tests.js
  network-api/networkapi/wagtailpages/factory/bannered_campaign_page.py
  network-api/networkapi/wagtailpages/factory/campaign_page.py
  network-api/networkapi/wagtailpages/factory/youtube_regrets_page.py
Labels: ready-to-merge

#4552 Fix Twitter icon color to black
  source/images/glyphs/twitter.svg
Labels: ready-to-merge

#4555 Allow any authenticated user to clear the PNI product cache
  network-api/networkapi/buyersguide/tests.py
  network-api/networkapi/buyersguide/views.py
Labels: ready-to-merge

#4554 Remove unused SCSS rules from mofo-bootstrap
  source/sass/global.scss
  source/sass/mofo-bootstrap/custom/components/_footer.scss
  source/sass/mofo-bootstrap/mofo-bootstrap.scss
  source/sass/mofo-bootstrap/overrides/_list-group.scss
  source/sass/mofo-bootstrap/overrides/_mixins.scss
  source/sass/mofo-bootstrap/overrides/_variables.scss
Labels: ready-to-merge

#4537 Let petition form's sticky CTA button stay on page a bit longer
  source/js/foundation/template-js-handler/window/sticky-cta.js
  source/sass/views/shared/sticky-cta.scss
Labels: ready-to-merge

#4556 give products a default sort order
  network-api/networkapi/buyersguide/migrations/0044_auto_20200423_2250.py
  network-api/networkapi/buyersguide/pagemodels/products/base.py
Labels: ready-to-merge

#4562 Remove extra ',' on PNI voting section
  source/js/buyers-guide/components/creep-vote/creep-vote.jsx
Labels: ready-to-merge

#4564 allow product updates to be featured
  network-api/networkapi/buyersguide/admin.py
  network-api/networkapi/buyersguide/migrations/0046_auto_20200427_2322.py
  network-api/networkapi/buyersguide/models.py
  network-api/networkapi/buyersguide/pagemodels/product_update.py
  network-api/networkapi/buyersguide/views.py
Labels: ready-to-merge

#4578 Remove 'shelljs' from devDependencies
  package.json
Labels: ready-to-merge

#4576 add validation and 400 codes for signups
  network-api/networkapi/campaign/tests.py
  network-api/networkapi/campaign/views.py
Labels: ready-to-merge

#4559 Clean up Bootstrap overrides (mostly around colours and type)
  network-api/networkapi/buyersguide/templates/bg_base.html
  network-api/networkapi/templates/pages/base.html
  network-api/networkapi/wagtailcustomization/templates/wagtailadmin/404.html
  source/js/components/join/join.scss
  source/sass/_variables.scss
  source/sass/buttons.scss
  source/sass/buyers-guide/bg-main.scss
  source/sass/buyers-guide/components/header.scss
  source/sass/buyers-guide/views/product.scss
  source/sass/components/nav.scss
  source/sass/components/primary-nav.scss
  source/sass/components/select-dropdown.scss
  source/sass/global.scss
  source/sass/main.scss
  source/sass/mixins.scss
  source/sass/mofo-bootstrap/_colors.scss
  source/sass/mofo-bootstrap/custom/_colors.scss
  source/sass/mofo-bootstrap/mofo-bootstrap.scss
  source/sass/mofo-bootstrap/overrides/_buttons.scss
  source/sass/mofo-bootstrap/overrides/_mixins.scss
  source/sass/mofo-bootstrap/overrides/_normalize.scss
  source/sass/mofo-bootstrap/overrides/_variables.scss
  source/sass/resets.scss
Labels: ready-to-merge

#4563 Position mozfest background video at center center
  source/sass/mozfest.scss
Labels: ready-to-merge

#4585 More SCSS cleanup
  source/images/line-art/play-icon.svg
  source/js/components/fellow-list/directory-filter-bar.scss
  source/sass/components/primary-nav.scss
  source/sass/global.scss
  source/sass/main.scss
  source/sass/mixins.scss
  source/sass/utilities.scss
Labels: ready-to-merge
