Repository MozillaFoundation/foundation.mozilla.org, pull requests merged in 2024-01, with the labels that each got.

#11628 5317 Integrate ticket block with tito
  network-api/networkapi/mozfest/blocks/tickets_block.py
  network-api/networkapi/mozfest/factory.py
  network-api/networkapi/mozfest/migrations/0041_use_event_object_on_ticket.py
  network-api/networkapi/mozfest/migrations/0042_ticket_releases.py
  network-api/networkapi/mozfest/models.py
  network-api/networkapi/mozfest/templates/fragments/blocks/tickets_block.html
  network-api/networkapi/wagtailpages/pagemodels/customblocks/tito_widget.py
  network-api/networkapi/wagtailpages/utils.py
  source/sass/mozfest.scss
Labels: mozfest 🎉

#11598 added donate landing and help page to percy tests
  .github/workflows/visual-regression-testing.yml
  tests/foundation-urls.js
  tests/visual.spec.js
Labels: run visual regression tests

#11636 PNI 'callout-box' style signup forms are now rendered using the new React components
  network-api/networkapi/templates/fragments/buyersguide/pni_newsletter_box.html
  source/js/common/inject-react/newsletter-signup-module.js
  source/js/components/newsletter-signup/atoms/description.jsx
  source/js/components/newsletter-signup/atoms/input-email.jsx
  source/js/components/newsletter-signup/atoms/select.jsx
  source/js/components/newsletter-signup/molecules/input-checkbox-with-label.jsx
  source/js/components/newsletter-signup/organisms/default-layout-signup.jsx
  source/js/components/newsletter-signup/organisms/form-specific-style.js
  tailwind-plugins/form-control.js
Labels: run visual regression tests

#11512 Consistent Meta ordering
  network-api/networkapi/wagtailpages/migrations/0116_fix_meta_ordering.py
  network-api/networkapi/wagtailpages/pagemodels/base.py
  network-api/networkapi/wagtailpages/pagemodels/blog/blog.py
  network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/detail_page.py
  network-api/networkapi/wagtailpages/templatetags/homepage_tags.py
Labels: run visual regression tests

#11658 Donate Help Form Integration tests
  network-api/networkapi/templates/donate/pages/help_page.html
  tests/integration/donate/help/001-help-form.spec.js
  tests/integration/donate/help/utility.js
Labels: run visual regression tests

#11706 Add Playwright tests for primary nav on mobile
  tests/integration/navigation/001-site-nav.spec.js
  tests/integration/navigation/002-mozfest-nav.spec.js
  tests/integration/navigation/003-pni-nav.spec.js
Labels: run visual regression tests

#11538 [PNI] Handle 100 average creepiness
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py
  network-api/networkapi/wagtailpages/tests/buyersguide/test_product_page_evaluation.py
Labels: run visual regression tests

#11711 Updated signup form on primary nav
  network-api/networkapi/templates/fragments/primary_nav.html
  source/js/common/inject-react/newsletter-signup-module.js
  source/js/components/join/join.jsx
  source/js/components/newsletter-signup/organisms/default-layout-signup.jsx
  source/js/components/newsletter-signup/organisms/form-specific-style.js
  source/js/components/newsletter-signup/organisms/with-submission-logic.jsx
  source/js/nav-newsletter.js
  tests/integration/foundation-homepage.spec.js
Labels: run visual regression tests

#11707 updated margin below DonateLandingPage featured image
  network-api/networkapi/templates/donate/pages/landing_page.html
Labels: run visual regression tests

#11713 Updated signup form on homepage's take action section
  network-api/networkapi/templates/fragments/footer.html
  network-api/networkapi/templates/fragments/primary_nav.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/take_action.html
  source/js/components/newsletter-signup/organisms/form-specific-style.js
Labels: run visual regression tests

#11727 added note about FRU 'test mode' to docs
  docs/stack.md
Labels: run visual regression tests

#11725 Updated signup form on YouTube Regrets Reporter page
  network-api/networkapi/wagtailpages/templates/wagtailpages/pages/youtube_regrets_reporter_page.html
  source/js/components/join/join.jsx
  source/js/components/newsletter-signup/organisms/form-specific-style.js
  source/sass/views/youtube-regrets-reporter.scss
Labels: run visual regression tests

#11729 Updated newsletter module on PNI consumer page's quiz section
  source/js/buyers-guide/components/product-quiz/product-quiz.jsx
  source/js/common/inject-react/newsletter-signup-module.js
  source/js/components/newsletter-signup/atoms/button-submit.jsx
  source/js/components/newsletter-signup/organisms/default-layout-signup.jsx
  source/js/components/newsletter-signup/organisms/form-specific-style.js
Labels: run visual regression tests

#11726 Bump django to 4.2 and Wagtail to 5.2
  dev-requirements.txt
  docs/upgrading.md
  network-api/networkapi/donate/pagemodels/customblocks/notice_block.py
  network-api/networkapi/donate/tests/customblocks/test_notice_block.py
  network-api/networkapi/events/tests.py
  network-api/networkapi/events/views.py
  network-api/networkapi/highlights/admin.py
  network-api/networkapi/highlights/urls.py
  network-api/networkapi/mozfest/blocks/cta_block.py
  network-api/networkapi/mozfest/blocks/mixed_content_block.py
  network-api/networkapi/news/admin.py
  network-api/networkapi/news/urls.py
  network-api/networkapi/settings.py
  network-api/networkapi/templates/icons/arrows-up-down.svg
  network-api/networkapi/templates/pages/reports/include/_list_block_types.html
  network-api/networkapi/templates/pages/reports/include/_list_page_types.html
  network-api/networkapi/urls.py
  network-api/networkapi/utility/middleware.py
  network-api/networkapi/utility/tests/test_redirects.py
  network-api/networkapi/wagtailcustomization/static/wagtail_modeltranslation/js/language_toggles.js
  network-api/networkapi/wagtailcustomization/static/wagtailadmin/css/custom-fix.css
  network-api/networkapi/wagtailcustomization/static/wagtailadmin/js/copy-helper.js
  network-api/networkapi/wagtailcustomization/tests/test_page_move_redirects.py
  network-api/networkapi/wagtailpages/migrations/0119_alter_banneredcampaigntag_tag_alter_blogpagetag_tag.py
  network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/article_page.py
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/homepage.py
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/blog_cta_card_with_text_block.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/image_teaser_block.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/listing.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/profile_directory.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/text_only_teaser.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/authors_index.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/detail_page.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/library_page.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/rcc/detail_page.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/research_hub/detail_page.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/research_hub/taxonomies.py
  network-api/networkapi/wagtailpages/pagemodels/profiles.py
  network-api/networkapi/wagtailpages/pagemodels/taxonomy.py
  network-api/networkapi/wagtailpages/tests/blog/test_blog_index.py
  network-api/networkapi/wagtailpages/tests/buyersguide/test_editorial_content_index.py
  network-api/networkapi/wagtailpages/tests/buyersguide/test_homepage.py
  network-api/networkapi/wagtailpages/tests/buyersguide/test_product_page_evaluation.py
  network-api/networkapi/wagtailpages/tests/test_utils.py
  network-api/networkapi/wagtailpages/utils.py
  network-api/networkapi/wagtailpages/wagtail_hooks.py
  requirements.in
  requirements.txt
Labels: run visual regression tests

#11754 Remove 'Or' from Wagtail login page
  network-api/networkapi/wagtailcustomization/templates/wagtailadmin/login.html
Labels: run visual regression tests

#11764 Bump postgres images from 13 to 15
  .github/workflows/continous-integration.yml
  app.json
  docker-compose.yml
Labels: run visual regression tests

#11765 Fix PNI Playwright tests
  tests/integration/pni.spec.js
  tests/integration/pni/search.spec.js
Labels: run visual regression tests

#11760 Convert snippets menu into groups
  network-api/networkapi/donate/wagtail_hooks.py
  network-api/networkapi/donate_banner/models.py
  network-api/networkapi/events/models.py
  network-api/networkapi/highlights/admin.py
  network-api/networkapi/highlights/models.py
  network-api/networkapi/mozfest/migrations/0045_alter_newslettersignupwithbackground_options.py
  network-api/networkapi/mozfest/models.py
  network-api/networkapi/mozfest/wagtail_hooks.py
  network-api/networkapi/news/admin.py
  network-api/networkapi/news/models.py
  network-api/networkapi/settings.py
  network-api/networkapi/templates/icons/flask.svg
  network-api/networkapi/templates/icons/heart.svg
  network-api/networkapi/templates/icons/mozfest.svg
  network-api/networkapi/templates/icons/newspaper.svg
  network-api/networkapi/templates/icons/pni.svg
  network-api/networkapi/templates/icons/ticket.svg
  network-api/networkapi/templates/icons/tito.svg
  network-api/networkapi/wagtailcustomization/views/snippet_chooser.py
  network-api/networkapi/wagtailpages/admin.py
  network-api/networkapi/wagtailpages/donation_modal.py
  network-api/networkapi/wagtailpages/migrations/0120_alter_petition_options.py
  network-api/networkapi/wagtailpages/pagemodels/base.py
  network-api/networkapi/wagtailpages/pagemodels/blog/blog_topic.py
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/call_to_action.py
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/products.py
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/taxonomies.py
  network-api/networkapi/wagtailpages/pagemodels/campaigns.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/rcc/taxonomies.py
  network-api/networkapi/wagtailpages/pagemodels/libraries/research_hub/taxonomies.py
  network-api/networkapi/wagtailpages/pagemodels/profiles.py
  network-api/networkapi/wagtailpages/pagemodels/pulse.py
  network-api/networkapi/wagtailpages/wagtail_hooks.py
Labels: run visual regression tests

#11761 Allow newsletter signup module to have two optional name fields & update newsletter module on Bannered Campaign Page
  network-api/networkapi/wagtailpages/templates/wagtailpages/bannered_campaign_page.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/tags/cta.html
  source/js/components/newsletter-signup/atoms/input-text.jsx
  source/js/components/newsletter-signup/organisms/default-layout-signup.jsx
  source/js/components/newsletter-signup/organisms/form-specific-style.js
  source/js/components/newsletter-signup/organisms/with-submission-logic.jsx
Labels: run visual regression tests

#11786 Update MozFest newsletter signup modules
  network-api/networkapi/mozfest/templates/fragments/blocks/newsletter_signup_with_background_block.html
  network-api/networkapi/mozfest/templates/fragments/blocks/sign_up_block.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/newsletter_signup_block.html
  source/js/components/join/join.jsx
  source/js/components/newsletter-signup/atoms/button-submit.jsx
  source/js/components/newsletter-signup/organisms/default-layout-signup.jsx
  source/js/components/newsletter-signup/organisms/form-specific-style.js
Labels: run visual regression tests

#11755 Mozfest - Incorrect meta text colour
  network-api/networkapi/mozfest/templates/fragments/mixed_content_card.html
Labels: run visual regression tests

#11756 Mozfest - Improve spacing between blocks
  network-api/networkapi/mozfest/templates/fragments/blocks/carousel_text_block.html
  network-api/networkapi/mozfest/templates/fragments/blocks/cta_block.html
  network-api/networkapi/mozfest/templates/fragments/blocks/newsletter_signup_with_background_block.html
  network-api/networkapi/mozfest/templates/fragments/blocks/tickets_block.html
  network-api/networkapi/mozfest/templates/partials/primary_hero.html
  network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/session_slider_block.html
Labels: run visual regression tests

#11708 Bump `urllib3` from 1.26.15 to 1.26.18
  dev-requirements.txt
  requirements.txt
Labels: engineering, backend, dependencies, run visual regression tests, pip

#11789 Bump Python from 3.9.9 to 3.11
  .github/workflows/continous-integration.yml
  Dockerfile
  app.json
  dev-requirements.in
  dev-requirements.txt
  mypy.ini
  network-api/networkapi/campaign/migrations/0001_squashed_0005_auto_20180626_1435.py
  network-api/networkapi/donate_banner/tests.py
  network-api/networkapi/highlights/migrations/0001_squashed_0007_nullify_homepage.py
  network-api/networkapi/news/migrations/0001_squashed_0013_remove_news_glyph.py
  network-api/networkapi/news/migrations/0002_remove_news_featured.py
  network-api/networkapi/news/migrations/0003_news_featured.py
  network-api/networkapi/s3_file_storage/storage.py
  network-api/networkapi/wagtailpages/pagemodels/buyersguide/utils.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/latest_profile_list.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/profile_by_id.py
  network-api/networkapi/wagtailpages/pagemodels/customblocks/profile_directory.py
  network-api/networkapi/wagtailpages/pagemodels/index.py
  network-api/networkapi/wagtailpages/pagemodels/profiles.py
  requirements.txt
  runtime.txt
  tasks.py
Labels: run visual regression tests
